### ISSUE TITLE
White screen and reboot Chameleon Mojave

### ISSUE THREAD

**Issue by 0xSerhii** [chris1111/Chameleon-macOS-Mojave-USB#1]
Hello, I installed MacOs Mojave 10.14.6 through your installer. Installation went well when I launched Mojave with the -v flag, all diagnostic tests pass, a white screen appears with the apple logo, then 2-4 seconds and reboots.

But when I run through your Post Install
High Sierra 10.12.6 it starts without rebooting

I have been struggling with this problem for several days, please help

My laptop https://www.notebookcheck.net/Review-Samsung-R730-JT06-Notebook.50611.0.html

**Comment by chris1111** [comment]
Release for macOS Mojave 10.14 6 (18G103)
This is what you have ?

**Comment by 0xSerhii** [comment]
**Yes, I downloaded yesterday from the App Store and make a bootable USB flash drive through**

System Software Overview:
  System Version:	**macOS 10.12.6 (16G29)**
  Kernel Version:	Darwin 16.7.0

[Also want to attach my Extra folder](https://drive.google.com/file/d/1PEpDihRdZINGMrOLk2BIzhlTDEhK4vOm/view?usp=sharing)

**Comment by chris1111** [comment]
Chameleon macOS Mojave is Release for macOS Mojave 10.14 6 (18G103)

You have to wait for the next release

**Comment by chris1111** [comment]
I will make some test tonight

**Comment by zaitsev1** [comment]
Am I using the correct version of your soft?

https://github.com/chris1111/Chameleon-macOS-Mojave-USB/releases/tag/V2

**Comment by chris1111** [comment]
You issue is relate to your hardware the GeForce G 310M is not support on Mojave and Catalina
Its complicated, you have to read about that . . . . .  and using the Patch Nvidia macOS Mojave ( Legacy Video patch)

**Comment by 0xSerhii** [comment]
Thank you very much for the advice, I will try, if possible, I will let you know
